[package]
name = "holad"
version = "2.0.3"
description = "Holad Music Player"
authors = ["FHRha"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"
default-run = "Holad"

[[bin]]
name = "Holad"
path = "src/main.rs"

[lib]
name = "holad_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = ["protocol-asset", "tray-icon", "image-png"] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-shell = "2.3.5"
tauri-plugin-fs = "2.5.1"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
ureq = { version = "2.10", features = ["tls"] }
[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_ProcessStatus"
] }

